[package]
name = "game"
version = "0.0.1"
authors = ["Dan Spencer <dan@atomicpotato.net>"]

[lib]
name = "game"
path = "lib.rs"

[dependencies]
rand = "0.3"
num = "0.1"

[dependencies.util]
path = "../util"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
