[package]
name = "opengl_util"
version = "0.0.1"
authors = ["Dan Spencer <dan@atomicpotato.net>"]

[[lib]]
name = "opengl_util"
path = "lib.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.lodepng]
git = "https://github.com/pornel/lodepng-rust"
